### ISSUE TITLE
`theory.createSecretAchievement` method does not support categories

### ISSUE THREAD

**Issue by zPeanut** [conicgames/theory-sdk#7]
while developing eulers formula, ive noticed that when trying to assign a secret achievement a category, i get this:

![image](https://user-images.githubusercontent.com/25800857/166822573-9fc40683-276c-45c9-927b-e4aa6d4e4749.png)
![image](https://user-images.githubusercontent.com/25800857/166822594-158bc9da-2aa0-4e4c-9db7-7f912171b189.png)

the method does not support having this many arguments.

**Comment by conicgames** [comment]
Thanks! I just added it to the API.
